# Generated by Django 5.0.6 on 2025-08-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='hash id'),
        ),
    ]
