# Generated by Django 5.0.6 on 2025-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='hash id'),
        ),
    ]
