# Generated by Django 5.0.6 on 2025-08-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('group', 'Group'), ('company', 'Company')], default='company', max_length=20),
        ),
    ]
