# Generated by Django 5.0.6 on 2025-08-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Dono'), ('admin', 'Administrador'), ('member', 'Membro'), ('readonly', 'Somente Leitura')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('group', 'Grupos'), ('company', 'Empresas')], default='company', max_length=20),
        ),
    ]
