# Generated by Django 5.0.6 on 2025-08-25 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=60, verbose_name='Complemento')),
                ('district', models.CharField(max_length=80, verbose_name='Bairro')),
                ('city_name', models.CharField(max_length=120, verbose_name='Cidade')),
                ('city_ibge_code', models.CharField(help_text='Código IBGE (7 dígitos)', max_length=7, verbose_name='Código IBGE')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('postal_code', models.CharField(help_text='CEP (8 dígitos)', max_length=8, verbose_name='CEP')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'indexes': [models.Index(fields=['city_ibge_code'], name='company_add_city_ib_ff2411_idx'), models.Index(fields=['state'], name='company_add_state_df620c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, max_length=255, verbose_name='Nome Fantasia')),
                ('tax_regime', models.CharField(choices=[('simples', 'Simples Nacional'), ('simples_excesso', 'Simples Nacional – Excesso sublimite'), ('presumido', 'Lucro Presumido'), ('real', 'Lucro Real')], max_length=30, verbose_name='Regime Tributário')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('state_registration', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Estadual')),
                ('municipal_registration', models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal')),
                ('is_matrix', models.BooleanField(default=False)),
                ('environment_default', models.CharField(choices=[('production', 'Production'), ('homologation', 'Homologation')], default='production', max_length=20, verbose_name='Ambiente Padrão')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='company.address', verbose_name='Endereço')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Estabelecimento',
                'verbose_name_plural': 'Estabelecimentos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('ncm', models.CharField(help_text='NCM (8 dígitos)', max_length=8, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=9, verbose_name='CEST')),
                ('cfop_sale', models.CharField(blank=True, max_length=10, verbose_name='CFOP Venda')),
                ('unit', models.CharField(default='UN', max_length=6, verbose_name='Unidade')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de Custo')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço de Venda')),
                ('cest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Alíquota CEST')),
                ('origin', models.IntegerField(default=0, help_text='Origem (0 a 8)', verbose_name='Origem Mercadoria')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='company.company', verbose_name='Empresa')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.AddConstraint(
            model_name='establishment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_matrix', True)), fields=('company',), name='unique_matrix_per_company'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('company', 'name')},
        ),
    ]
