# Generated by Django 5.0.6 on 2025-08-26 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='establishment',
            old_name='active',
            new_name='is_active',
        ),
    ]
