# Generated by Django 5.0.6 on 2025-08-28 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_active_establishment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
