# Generated by Django 5.0.6 on 2025-08-29 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='establishments', to='company.address', verbose_name='Endereço'),
        ),
    ]
